# digital_skeptic/report.py
from .types import AnalysisResult

HEADER = "# Critical Analysis Report\n"


def to_markdown(result: AnalysisResult) -> str:
    lines = [HEADER, f"**Article:** {result.title}\n", f"**URL:** {result.url}\n"]

    # --- Core Claims ---
    lines.append("\n## Core Claims\n")
    if result.core_claims:
        for c in result.core_claims:
            lines.append(f"- {c.text}\n")
    else:
        lines.append("- (No clear verifiable claims detected)\n")

    # --- Language & Tone ---
    lines.append("\n## Language & Tone Analysis\n")
    lines.append(f"**Classification:** {result.tone.classification}\n\n")
    if result.tone.details:
        lines.append(f"{result.tone.details}\n")

    # --- Red Flags ---
    lines.append("\n## Potential Red Flags\n")
    if result.red_flags:
        for rf in result.red_flags:
            lines.append(f"- **{rf.label}:** {rf.explanation}\n")
    else:
        lines.append("- No strong red flags detected.\n")

    # --- Verification Questions ---
    lines.append("\n## Verification Questions\n")
    for i, q in enumerate(result.questions, start=1):
        lines.append(f"{i}. {q.question}\n")

    # --- Entities (stand-out feature) ---
    lines.append("\n## Entities to Investigate\n")
    ppl = ", ".join(result.entities.people) or "(none)"
    orgs = ", ".join(result.entities.orgs) or "(none)"
    locs = ", ".join(result.entities.locations) or "(none)"
    lines.append(f"- **People:** {ppl}\n")
    lines.append(f"- **Organizations:** {orgs}\n")
    lines.append(f"- **Locations:** {locs}\n")

    # --- Counter-Argument (stand-out feature) ---
    if result.counter_argument:
        lines.append("\n## Opposing Viewpoint (Counter-Argument Simulation)\n")
        lines.append(result.counter_argument.strip() + "\n")

    # --- Footer ---
    lines.append("\n---\n")
    lines.append("*Generated by Digital Skeptic AI.*\n")

    return "".join(lines)
